---
title: "new-enrollment"
author: "paolo pasco"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(googlesheets4)
library(fs)
library(readxl)
library(janitor)
library(gt)
```

```{r download, echo=FALSE}

url_current <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.25.20_0.xlsx"

url_old <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19_0.xlsx"

download.file(url = url_current, destfile = "current.xlsx")

download.file(url = url_old, destfile = "old.xlsx")

current <- read_xlsx("current.xlsx", skip=3) %>%
  clean_names() %>%
  filter(!is.na(course_name))

old <- read_xlsx("old.xlsx", skip=3) %>%
  clean_names() %>%
  filter(!is.na(course_name)) %>%
  select(course_id)
  
new_courses <- current %>% 
  anti_join(old, by="course_id") %>%
  arrange(desc(total)) %>%
  slice(1:5) %>%
  gt() %>%
  tab_header(
    title = md("**Top 5 Enrolled Concentrations**")
  )

new_courses
```